/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.blogspot.defik.zxandroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int spectrum=0x7f060000;
        public static final int text=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int knightlore=0x7f040000;
        public static final int sinclair48=0x7f040001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int menu_pause=0x7f050003;
        public static final int menu_resume=0x7f050004;
        public static final int menu_start=0x7f050001;
        public static final int menu_stop=0x7f050002;
        public static final int zxandroid_layout_text_text=0x7f050005;
    }
}
